### ISSUE TITLE
discuss logic inside fly.handle() function

### ISSUE THREAD

**Issue by asclepiusaka** [AS-CSLW/FlySimulation#2]

**Comment by soowonch** [comment]
Hello, Guys,
I think it is quite late, but I think the idea changing fly to particle which having bad smell. 
Since the fly does not have destination and it has direction and velocity, **the simulation becomes continuous rather than discrete.** That's why it is difficult to make handle() function for me.

If we change fly into particle and a fly killer into a suction, we can maintain the Airport simulation concept and the new idea about the best position of suction along with the different room. This is because the particles having bad smell can have destination which is suction because a suction will inhale the particles.

Please consider it.

**Comment by soowonch** [comment]
Nevertheless, if we stick to the fly simulation,

I think changeDirection event and KnockIntoWall event can be merged like:

fly.handle(){
case FlyEvent.changeDirection:
//Random direction fly
//get velocity
//create line of fly's direction
//when wall lines' (x,y) and fly line's (x,y) are same, fly changes their direction into: slope is -'slope of the previous fly line', pass (x,y) which is intersection of previous fly line and wall.
break;

case FlyEvent.flyIntoTrap:
//killing time
//println a fly is killed in x seconds
break;
	}

**Comment by mxynapoleon** [comment]
do you think the professor would approve this? maybe..because he actually does not care
